# Numpy

It is a package for scientific computing
1. Multidimensional array
2. Methods for processing arrays
3. Element by element operations
4. Mathematical operations like logical, Fourier transform, shape manipulation, linear algebra and random number generation

```python 
np.array()
```

In [1]:
import numpy as np

In [2]:
# Create a single dimensional array
a = np.array([10,39,58])

In [3]:
type(a)

numpy.ndarray

In [4]:
print(a)

[10 39 58]


In [5]:
# Create a ndimensional array
am = np.array([[10,20], [30,40]])
print(am)

[[10 20]
 [30 40]]


In [6]:
# Create a ndarray by wrapping a list
l = [1,2,3,4,5]
type(l),l

(list, [1, 2, 3, 4, 5])

In [7]:
array = np.array(l)

In [8]:
type(array)

numpy.ndarray

In [9]:
print(array)

[1 2 3 4 5]


In [10]:
# Another way to create an array
ar = np.arange(1,20)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


```python 
numpy.arange() 
``` 
A function within the NumPy library in Python used to create an array of evenly spaced values within a specified interval. 
#### Syntax
```python 
numpy.arange([start, ]stop, [step, ], dtype=None)
```

In [11]:
ar = np.arange(1,20, 0.5)
print(ar)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [12]:
# Create a 5x5 array of zeros
array_zeros = np.zeros((5,5))
print(array_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Create a lineary spaced vector
```python 
np.linspace(start, stop, num, endpoint, retstep, dtype)
```

In [13]:
# Example
data = np.linspace(0,10, 20)
print(data)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


#### Convert a linear array into 2D or 3D array


In [15]:
array = np.zeros(9)
array3d = array.reshape((3,3))
print(array3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
array = np.zeros(9)
array3d = array.reshape((3,3))
arraylin = array3d.ravel()
print(arraylin)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Numpy array indexing

Numpy array indexing is identical to Python's indexing scheme

### Slicing of Numpy array
1. Slicing items beginning with a specified index
2. Slicing items until a specific index
3. Slicing items in a range
4. Extracting specific rows and columns using Slicing

### NumPy Array Attributes

- shape() == returns a tuple consisting of array dimension
- ndim() == returns the number of array dimensions
- itemsize() == Returns the length of each element of array in bytes

In [21]:
array = np.zeros((3,3))
print(array.shape)
print(array.ndim)
print(a.itemsize)

(3, 3)
2
8


In [22]:
import numpy as np

#order='C' (C-style, row-major): 
#This is the default behavior. Elements are filled into the new array row by row. The last index changes fastest.
arr_c = np.arange(6).reshape((2, 3), order='C')
print(f"C-order reshape: \n{arr_c}")

#order='F' (Fortran-style, column-major): 
#Elements are filled into the new array column by column. The first index changes fastest.
arr_f = np.arange(6).reshape((2, 3), order='F')
print(f"F-order reshape: \n{arr_f}")

#order='A' (Any-order): This option attempts to use the original array's memory layout if it's already C-contiguous or F-contiguous 
#and compatible with the new shape. If not, it defaults to 'C' order.
arr_a = np.arange(6).reshape((2, 3), order='A')
print(f"A-order reshape: \n{arr_f}")

C-order reshape: 
[[0 1 2]
 [3 4 5]]
F-order reshape: 
[[0 2 4]
 [1 3 5]]
A-order reshape: 
[[0 2 4]
 [1 3 5]]


### Importing data from file
NumPy provides the option of importing data from files directly into ndarray using the loadtxt function
The savetxt function can be used to write data from an array into a text file

In [24]:
#import os
#print(os.listdir('../input'))
arr_txt = np.loadtxt('../input/data_file.txt')
np.savetxt('newfilex.txt', arr_txt)


# NumPy arrays can be dumped into CSV files using the savetxt function and the comma delimiter
# The genfromtxt function can be used to read data from a CSV file into a NumPy array
arr_csv = np.genfromtxt('../input/Hurricanes.csv', delimiter = ',')
np.savetxt('newfilex.csv', arr_csv, delimiter = ',')

FileNotFoundError: ../input/data_file.txt not found.

### random()

Random values in a given shape.


* numpy.random.rand : Random values in a given shape.
* numpy.random.randint(low, high=None, size=None, dtype=int) : Return random integers from low (inclusive) to high (exclusive).
* numpy.random.randn : Return a sample (or samples) from the “standard normal” distribution.
* random.random(size=None) : Return random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random API.

In [25]:
np.random.rand(3)

array([0.04097544, 0.3578473 , 0.75469281])

In [26]:
np.random.rand(3,2)

array([[0.57601046, 0.95926437],
       [0.7992081 , 0.03918249],
       [0.79212163, 0.57903831]])

In [35]:
np.random.randint(2, size=10)

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1])

In [36]:
np.random.random(size=10)

array([0.60371222, 0.46106994, 0.68673617, 0.23684868, 0.96434279,
       0.8561344 , 0.95479584, 0.94760739, 0.1395383 , 0.40334199])