# Numpy

It is a package for scientific computing
1. Multidimensional array
2. Methods for processing arrays
3. Element by element operations
4. Mathematical operations like logical, Fourier transform, shape manipulation, linear algebra and random number generation

```python 
np.array()
```

In [1]:
import numpy as np

In [7]:
# Create a single dimensional array
a = np.array([10,39,58])

In [8]:
type(a)

numpy.ndarray

In [9]:
print(a)

[10 39 58]


In [10]:
# Create a ndimensional array
am = np.array([[10,20], [30,40]])
print(am)

[[10 20]
 [30 40]]


In [15]:
# Create a ndarray by wrapping a list
l = [1,2,3,4,5]
type(l),l

(list, [1, 2, 3, 4, 5])

In [12]:
array = np.array(l)

In [13]:
type(array)

numpy.ndarray

In [14]:
print(array)

[1 2 3 4 5]


In [18]:
# Another way to create an array
ar = np.arange(1,20)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


```python 
numpy.arange() 
``` 
A function within the NumPy library in Python used to create an array of evenly spaced values within a specified interval. 
#### Syntax
```python 
numpy.arange([start, ]stop, [step, ], dtype=None)
```

In [22]:
ar = np.arange(1,20, 0.5)
print(ar)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [24]:
# Create a 5x5 array of zeros
array_zeros = np.zeros((5,5))
print(array_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Create a lineary spaced vector
```python 
np.linspace(start, stop, num, endpoint, retstep, dtype)
```

In [35]:
# Example
data = np.linspace(0,10, 20)
print(data)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


#### Convert a linear array into 2D or 3D dimensional array

#### Convert a linear array into 2D or 3D array


In [39]:
    import numpy as np

    arr_c = np.arange(6).reshape((2, 3), order='C')
    print(f"C-order reshape: \n{arr_c}")

    arr_f = np.arange(6).reshape((2, 3), order='F')
    print(f"F-order reshape: \n{arr_f}")

    arr_a = np.arange(6).reshape((2, 3), order='A')
    print(f"A-order reshape: \n{arr_f}")

C-order reshape: 
[[0 1 2]
 [3 4 5]]
F-order reshape: 
[[0 2 4]
 [1 3 5]]
A-order reshape: 
[[0 2 4]
 [1 3 5]]
